INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Cracked corn')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Wheat')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Barley')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Oats')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Rice')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Milo Seeds')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Birdseeds')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Grapes')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Nut hearts')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Frozen peas')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Corn')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Earthworm')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Mealworm')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Chopped Lettuce')
INSERT INTO dbo.DuckFood ( [FoodName]) VALUES ('Vegetable trimming')


INSERT INTO dbo.FeedLocation ([FeedLocationName]) VALUES ('Inside')
INSERT INTO dbo.FeedLocation ([FeedLocationName]) VALUES ('Outside')
INSERT INTO dbo.FeedLocation ([FeedLocationName]) VALUES ('Park')